name: 'ruby'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ruby:
    +schema: analytics
    +materialized: table

    daily_metrics:
      +description: "Daily KPIs including DAU, revenue, ads, and spend"

    ecpms:
      +description: "Aggregated ad impressions and revenue by campaign/ad type"

    purchase_metrics:
      +description: "Aggregated IAP revenue and payers by product/country/platform"
