version: 2

models:
  - name: daily_metrics  
    description: "Daily metrics by install and event date."
    columns:
      - name: launch_date
        description: "Campaign launch date"

      - name: install_date
        description: "Player install date"

      - name: country_name
        description: "Country of the player"

      - name: platform
        description: "Platform (iOS / Android)"

      - name: ua_category
        description: "User acquisition category"
      
      - name: ua_network
        description: "UA network"
      
      - name: campaign
        description: "Campaign name"
      
      - name: event_date
        description: "Event date"

      - name: cohort_day
        description: "Days since install"

      - name: dau
        description: "Daily active users"

      - name: iap_dau
        description: "Daily active payers"

      - name: iap_count
        description: "Number of in-app purchases"

      - name: iap_revenue
        description: "Revenue from in-app purchases"

      - name: rw_imp_count
        description: "Rewarded impressions"

      - name: int_imp_count
        description: "Interstitial impressions"

      - name: ad_revenue_tracked
        description: "Ad revenue (tracked)"

      - name: ad_revenue_reported
        description: "Ad revenue (reported by network)"

      - name: total_revenue
        description: "Total revenue (IAP + Ads)"

      - name: playtime
        description: "Total playtime in minutes"

      - name: spend
        description: "UA spend for the campaign/date"

      - name: cum_total_revenue
        description: "Cumulative revenue up to that day"
